# Nylo - Micro-framework for Flutter.
#
# Website: https://nylo.dev
# Official repository: https://github.com/nylo-core/nylo
# Author: Anthony Gordon <https://github.com/agordn52>

name: avaquran_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  google_fonts: ^8.1.0
  analyzer: ^10.0.1
  intl: ^0.20.2
  nylo_framework: ^7.1.17
  cupertino_icons: ^1.0.9
  font_awesome_flutter: ^11.0.0
  get: ^4.7.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.4.1
  audioplayers: ^6.6.0
  multiavatar: ^0.1.5
  flutter_svg: ^2.3.0
  webview_flutter: ^4.13.1
  share_plus: ^12.0.2
  shimmer: ^3.0.0
  shared_preferences: ^2.5.5
  flutter_html: ^3.0.0-beta.2
  just_audio: ^0.9.44
  audio_service: ^0.18.17
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  geolocator: ^13.0.2
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  # The following line 'flutter_lints' activates a set of recommended lints.
#  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  rename: ^3.1.0

# APP ICON - public/app_icon/icon.png
# Build icons: "dart run flutter_launcher_icons"
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/icon_tbg.png"
  remove_alpha_ios: true


dependency_overrides:
  characters: 1.4.0

flutter:



  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/app_icon/
    - lang/
